"""add day_plans and pattern_goals

Revision ID: 0903f6d291ab
Revises: a3bb66cde5d6
Create Date: 2026-08-01 16:53:57.610220

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0903f6d291ab'
down_revision = 'a3bb66cde5d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('warmup_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rounds_target', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_day_plans_id'), 'day_plans', ['id'], unique=False)
    op.create_index(op.f('ix_day_plans_name'), 'day_plans', ['name'], unique=False)
    op.create_index(op.f('ix_day_plans_user_id'), 'day_plans', ['user_id'], unique=False)
    op.create_table('pattern_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_plan_id', sa.Integer(), nullable=False),
    sa.Column('pattern_id', sa.Integer(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('target_sets', sa.Integer(), nullable=True),
    sa.Column('rep_range_min', sa.Integer(), nullable=True),
    sa.Column('rep_range_max', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['day_plan_id'], ['day_plans.id'], ),
    sa.ForeignKeyConstraint(['pattern_id'], ['movement_patterns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pattern_goals_day_plan_id'), 'pattern_goals', ['day_plan_id'], unique=False)
    op.create_index(op.f('ix_pattern_goals_id'), 'pattern_goals', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pattern_goals_id'), table_name='pattern_goals')
    op.drop_index(op.f('ix_pattern_goals_day_plan_id'), table_name='pattern_goals')
    op.drop_table('pattern_goals')
    op.drop_index(op.f('ix_day_plans_user_id'), table_name='day_plans')
    op.drop_index(op.f('ix_day_plans_name'), table_name='day_plans')
    op.drop_index(op.f('ix_day_plans_id'), table_name='day_plans')
    op.drop_table('day_plans')
    # ### end Alembic commands ###
