"""add is_combination field to exercises

Revision ID: 1176bac92d55
Revises: 98ca78ffdf3e
Create Date: 2026-01-14 04:56:02.813045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1176bac92d55'
down_revision = '98ca78ffdf3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('is_combination', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'is_combination')
    # ### end Alembic commands ###
