"""add bodyweight readings and fraction

Revision ID: 11ddf1911138
Revises: b7c14e2a9f30
Create Date: 2026-08-11 21:53:19.451399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11ddf1911138'
down_revision = 'b7c14e2a9f30'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bodyweight_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(), server_default='manual', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'recorded_at', 'source', name='uq_bodyweight_user_instant_source')
    )
    op.create_index(op.f('ix_bodyweight_readings_id'), 'bodyweight_readings', ['id'], unique=False)
    op.create_index(op.f('ix_bodyweight_readings_recorded_at'), 'bodyweight_readings', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_bodyweight_readings_user_id'), 'bodyweight_readings', ['user_id'], unique=False)
    op.add_column('exercises', sa.Column('bodyweight_fraction', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'bodyweight_fraction')
    op.drop_index(op.f('ix_bodyweight_readings_user_id'), table_name='bodyweight_readings')
    op.drop_index(op.f('ix_bodyweight_readings_recorded_at'), table_name='bodyweight_readings')
    op.drop_index(op.f('ix_bodyweight_readings_id'), table_name='bodyweight_readings')
    op.drop_table('bodyweight_readings')
    # ### end Alembic commands ###
