"""add injury types and user injuries

Revision ID: 4eedf400be74
Revises: a8639382ac85
Create Date: 2026-01-06 16:33:06.583381

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4eedf400be74'
down_revision = 'a8639382ac85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('injury_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('body_area', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity_levels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_injury_types_id'), 'injury_types', ['id'], unique=False)
    op.create_table('movement_restrictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restriction_type', sa.String(), nullable=False),
    sa.Column('restriction_value', sa.String(), nullable=False),
    sa.Column('severity_threshold', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movement_restrictions_id'), 'movement_restrictions', ['id'], unique=False)
    op.create_table('injury_movement_restrictions',
    sa.Column('injury_type_id', sa.Integer(), nullable=False),
    sa.Column('restriction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['injury_type_id'], ['injury_types.id'], ),
    sa.ForeignKeyConstraint(['restriction_id'], ['movement_restrictions.id'], ),
    sa.PrimaryKeyConstraint('injury_type_id', 'restriction_id')
    )
    op.create_table('user_injuries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('injury_type_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['injury_type_id'], ['injury_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_injuries_id'), 'user_injuries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_injuries_id'), table_name='user_injuries')
    op.drop_table('user_injuries')
    op.drop_table('injury_movement_restrictions')
    op.drop_index(op.f('ix_movement_restrictions_id'), table_name='movement_restrictions')
    op.drop_table('movement_restrictions')
    op.drop_index(op.f('ix_injury_types_id'), table_name='injury_types')
    op.drop_table('injury_types')
    # ### end Alembic commands ###
