"""add enhanced fields to routine_slots

Revision ID: 5077e7889e05
Revises: a72f10231719
Create Date: 2026-01-04 14:57:41.295350

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5077e7889e05'
down_revision = 'a72f10231719'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use existing slottype enum if it exists, otherwise create it
    slottype_enum = sa.Enum('standard', 'warmup', 'finisher', 'active_recovery', 'wildcard', name='slottype', create_type=False)
    op.execute("DO $$ BEGIN CREATE TYPE slottype AS ENUM ('standard', 'warmup', 'finisher', 'active_recovery', 'wildcard'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    op.add_column('routine_slots', sa.Column('slot_type', slottype_enum, nullable=False, server_default='standard'))
    op.add_column('routine_slots', sa.Column('slot_template_id', sa.Integer(), nullable=True))
    op.add_column('routine_slots', sa.Column('time_limit_seconds', sa.Integer(), nullable=True))
    op.add_column('routine_slots', sa.Column('required_equipment_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('routine_slots', sa.Column('target_sets', sa.Integer(), nullable=True))
    op.add_column('routine_slots', sa.Column('target_reps_min', sa.Integer(), nullable=True))
    op.add_column('routine_slots', sa.Column('target_reps_max', sa.Integer(), nullable=True))
    op.add_column('routine_slots', sa.Column('target_weight', sa.Float(), nullable=True))
    op.add_column('routine_slots', sa.Column('target_time_seconds', sa.Integer(), nullable=True))
    op.add_column('routine_slots', sa.Column('target_rest_seconds', sa.Integer(), nullable=True))
    op.add_column('routine_slots', sa.Column('progression_rule', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_foreign_key(None, 'routine_slots', 'slot_templates', ['slot_template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'routine_slots', type_='foreignkey')
    op.drop_column('routine_slots', 'progression_rule')
    op.drop_column('routine_slots', 'target_rest_seconds')
    op.drop_column('routine_slots', 'target_time_seconds')
    op.drop_column('routine_slots', 'target_weight')
    op.drop_column('routine_slots', 'target_reps_max')
    op.drop_column('routine_slots', 'target_reps_min')
    op.drop_column('routine_slots', 'target_sets')
    op.drop_column('routine_slots', 'required_equipment_ids')
    op.drop_column('routine_slots', 'time_limit_seconds')
    op.drop_column('routine_slots', 'slot_template_id')
    op.drop_column('routine_slots', 'slot_type')
    # ### end Alembic commands ###
