"""initial_schema

Revision ID: 5084736020fd
Revises: 
Create Date: 2026-01-04 13:07:35.922528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5084736020fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_id'), 'equipment', ['id'], unique=False)
    op.create_index(op.f('ix_equipment_name'), 'equipment', ['name'], unique=True)
    op.create_table('equipment_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('equipment_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_profiles_id'), 'equipment_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_equipment_profiles_is_default'), 'equipment_profiles', ['is_default'], unique=False)
    op.create_index(op.f('ix_equipment_profiles_name'), 'equipment_profiles', ['name'], unique=False)
    op.create_table('muscle_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['muscle_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_muscle_groups_id'), 'muscle_groups', ['id'], unique=False)
    op.create_index(op.f('ix_muscle_groups_name'), 'muscle_groups', ['name'], unique=False)
    op.create_table('routine_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('routine_type', sa.String(), nullable=True),
    sa.Column('workout_style', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routine_templates_id'), 'routine_templates', ['id'], unique=False)
    op.create_index(op.f('ix_routine_templates_name'), 'routine_templates', ['name'], unique=False)
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('primary_equipment_id', sa.Integer(), nullable=True),
    sa.Column('secondary_equipment_id', sa.Integer(), nullable=True),
    sa.Column('primary_equipment_count', sa.Integer(), nullable=True),
    sa.Column('secondary_equipment_count', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Enum('BEGINNER', 'NOVICE', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='difficultylevel'), nullable=True),
    sa.Column('exercise_classification', sa.String(), nullable=True),
    sa.Column('posture', sa.String(), nullable=True),
    sa.Column('movement_pattern_1', sa.String(), nullable=True),
    sa.Column('movement_pattern_2', sa.String(), nullable=True),
    sa.Column('movement_pattern_3', sa.String(), nullable=True),
    sa.Column('plane_of_motion_1', sa.String(), nullable=True),
    sa.Column('plane_of_motion_2', sa.String(), nullable=True),
    sa.Column('plane_of_motion_3', sa.String(), nullable=True),
    sa.Column('body_region', sa.String(), nullable=True),
    sa.Column('force_type', sa.String(), nullable=True),
    sa.Column('mechanics', sa.String(), nullable=True),
    sa.Column('laterality', sa.String(), nullable=True),
    sa.Column('short_demo_url', sa.String(), nullable=True),
    sa.Column('in_depth_url', sa.String(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('base_exercise_id', sa.Integer(), nullable=True),
    sa.Column('variant_type', sa.String(), nullable=True),
    sa.Column('is_custom', sa.String(), nullable=True),
    sa.Column('default_sets', sa.Integer(), nullable=True),
    sa.Column('default_reps', sa.Integer(), nullable=True),
    sa.Column('default_weight', sa.Float(), nullable=True),
    sa.Column('default_time_seconds', sa.Integer(), nullable=True),
    sa.Column('default_rest_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['base_exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['primary_equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['secondary_equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_id'), 'exercises', ['id'], unique=False)
    op.create_index(op.f('ix_exercises_name'), 'exercises', ['name'], unique=True)
    op.create_table('workout_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routine_template_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'COMPLETED', 'ABANDONED', name='workoutstate'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['routine_template_id'], ['routine_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_sessions_id'), 'workout_sessions', ['id'], unique=False)
    op.create_table('exercise_muscle_groups',
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('muscle_group_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['muscle_group_id'], ['muscle_groups.id'], ),
    sa.PrimaryKeyConstraint('exercise_id', 'muscle_group_id')
    )
    op.create_table('routine_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routine_template_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('muscle_group_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('superset_tag', sa.String(), nullable=True),
    sa.Column('selected_exercise_id', sa.Integer(), nullable=True),
    sa.Column('workout_style', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['routine_template_id'], ['routine_templates.id'], ),
    sa.ForeignKeyConstraint(['selected_exercise_id'], ['exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routine_slots_id'), 'routine_slots', ['id'], unique=False)
    op.create_table('workout_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_session_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=True),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('slot_state', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'SKIPPED', name='slotstate'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['routine_slots.id'], ),
    sa.ForeignKeyConstraint(['workout_session_id'], ['workout_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_exercises_id'), 'workout_exercises', ['id'], unique=False)
    op.create_table('heart_rate_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_session_id', sa.Integer(), nullable=True),
    sa.Column('workout_exercise_id', sa.Integer(), nullable=True),
    sa.Column('slot_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('avg_hr', sa.Float(), nullable=True),
    sa.Column('peak_hr', sa.Integer(), nullable=True),
    sa.Column('min_hr', sa.Integer(), nullable=True),
    sa.Column('time_in_fat_burn', sa.Integer(), nullable=True),
    sa.Column('time_in_cardio', sa.Integer(), nullable=True),
    sa.Column('time_in_peak', sa.Integer(), nullable=True),
    sa.Column('time_in_maximum', sa.Integer(), nullable=True),
    sa.Column('fat_burn_percentage', sa.Float(), nullable=True),
    sa.Column('cardio_percentage', sa.Float(), nullable=True),
    sa.Column('peak_percentage', sa.Float(), nullable=True),
    sa.Column('maximum_percentage', sa.Float(), nullable=True),
    sa.Column('trend', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['slot_id'], ['routine_slots.id'], ),
    sa.ForeignKeyConstraint(['workout_exercise_id'], ['workout_exercises.id'], ),
    sa.ForeignKeyConstraint(['workout_session_id'], ['workout_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heart_rate_analytics_id'), 'heart_rate_analytics', ['id'], unique=False)
    op.create_index(op.f('ix_heart_rate_analytics_level'), 'heart_rate_analytics', ['level'], unique=False)
    op.create_table('heart_rate_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_exercise_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('bpm', sa.Integer(), nullable=False),
    sa.Column('zone', sa.Enum('FAT_BURN', 'CARDIO', 'PEAK', 'MAXIMUM', name='heartratezone'), nullable=True),
    sa.ForeignKeyConstraint(['workout_exercise_id'], ['workout_exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heart_rate_readings_id'), 'heart_rate_readings', ['id'], unique=False)
    op.create_index(op.f('ix_heart_rate_readings_timestamp'), 'heart_rate_readings', ['timestamp'], unique=False)
    op.create_table('workout_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_exercise_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['workout_exercise_id'], ['workout_exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_sets_id'), 'workout_sets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_sets_id'), table_name='workout_sets')
    op.drop_table('workout_sets')
    op.drop_index(op.f('ix_heart_rate_readings_timestamp'), table_name='heart_rate_readings')
    op.drop_index(op.f('ix_heart_rate_readings_id'), table_name='heart_rate_readings')
    op.drop_table('heart_rate_readings')
    op.drop_index(op.f('ix_heart_rate_analytics_level'), table_name='heart_rate_analytics')
    op.drop_index(op.f('ix_heart_rate_analytics_id'), table_name='heart_rate_analytics')
    op.drop_table('heart_rate_analytics')
    op.drop_index(op.f('ix_workout_exercises_id'), table_name='workout_exercises')
    op.drop_table('workout_exercises')
    op.drop_index(op.f('ix_routine_slots_id'), table_name='routine_slots')
    op.drop_table('routine_slots')
    op.drop_table('exercise_muscle_groups')
    op.drop_index(op.f('ix_workout_sessions_id'), table_name='workout_sessions')
    op.drop_table('workout_sessions')
    op.drop_index(op.f('ix_exercises_name'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_id'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_routine_templates_name'), table_name='routine_templates')
    op.drop_index(op.f('ix_routine_templates_id'), table_name='routine_templates')
    op.drop_table('routine_templates')
    op.drop_index(op.f('ix_muscle_groups_name'), table_name='muscle_groups')
    op.drop_index(op.f('ix_muscle_groups_id'), table_name='muscle_groups')
    op.drop_table('muscle_groups')
    op.drop_index(op.f('ix_equipment_profiles_name'), table_name='equipment_profiles')
    op.drop_index(op.f('ix_equipment_profiles_is_default'), table_name='equipment_profiles')
    op.drop_index(op.f('ix_equipment_profiles_id'), table_name='equipment_profiles')
    op.drop_table('equipment_profiles')
    op.drop_index(op.f('ix_equipment_name'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_id'), table_name='equipment')
    op.drop_table('equipment')
    # ### end Alembic commands ###
