"""add movement_patterns

Revision ID: 51a278328365
Revises: e5b14fa30dfc
Create Date: 2026-08-01 16:30:00.103495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51a278328365'
down_revision = 'e5b14fa30dfc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movement_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('opposite_pattern_id', sa.Integer(), nullable=True),
    sa.Column('is_neutral', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['opposite_pattern_id'], ['movement_patterns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movement_patterns_id'), 'movement_patterns', ['id'], unique=False)
    op.create_index(op.f('ix_movement_patterns_slug'), 'movement_patterns', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movement_patterns_slug'), table_name='movement_patterns')
    op.drop_index(op.f('ix_movement_patterns_id'), table_name='movement_patterns')
    op.drop_table('movement_patterns')
    # ### end Alembic commands ###
