"""add staple_exercises and exercise_preferences

Revision ID: 59af238ed19e
Revises: 6c833617c7fe
Create Date: 2026-08-01 17:11:36.969437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59af238ed19e'
down_revision = '6c833617c7fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('preference', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'exercise_id', name='uq_pref_user_exercise')
    )
    op.create_index(op.f('ix_exercise_preferences_id'), 'exercise_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_exercise_preferences_user_id'), 'exercise_preferences', ['user_id'], unique=False)
    op.create_table('staple_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pattern_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['pattern_id'], ['movement_patterns.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'exercise_id', name='uq_staple_user_exercise')
    )
    op.create_index(op.f('ix_staple_exercises_id'), 'staple_exercises', ['id'], unique=False)
    op.create_index(op.f('ix_staple_exercises_pattern_id'), 'staple_exercises', ['pattern_id'], unique=False)
    op.create_index(op.f('ix_staple_exercises_user_id'), 'staple_exercises', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staple_exercises_user_id'), table_name='staple_exercises')
    op.drop_index(op.f('ix_staple_exercises_pattern_id'), table_name='staple_exercises')
    op.drop_index(op.f('ix_staple_exercises_id'), table_name='staple_exercises')
    op.drop_table('staple_exercises')
    op.drop_index(op.f('ix_exercise_preferences_user_id'), table_name='exercise_preferences')
    op.drop_index(op.f('ix_exercise_preferences_id'), table_name='exercise_preferences')
    op.drop_table('exercise_preferences')
    # ### end Alembic commands ###
