"""add training sessions, rounds, entries, sets

Revision ID: 6c833617c7fe
Revises: 0903f6d291ab
Create Date: 2026-08-01 17:02:16.825678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c833617c7fe'
down_revision = '0903f6d291ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day_plan_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.Enum('draft', 'active', 'completed', 'discarded', name='sessionstate'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['day_plan_id'], ['day_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_sessions_id'), 'training_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_training_sessions_user_id'), 'training_sessions', ['user_id'], unique=False)
    op.create_table('superset_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_superset_rounds_id'), 'superset_rounds', ['id'], unique=False)
    op.create_index(op.f('ix_superset_rounds_session_id'), 'superset_rounds', ['session_id'], unique=False)
    op.create_table('round_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('pattern_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['pattern_id'], ['movement_patterns.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['superset_rounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_round_entries_exercise_id'), 'round_entries', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_round_entries_id'), 'round_entries', ['id'], unique=False)
    op.create_index(op.f('ix_round_entries_pattern_id'), 'round_entries', ['pattern_id'], unique=False)
    op.create_index(op.f('ix_round_entries_round_id'), 'round_entries', ['round_id'], unique=False)
    op.create_table('entry_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('time_seconds', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['round_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entry_sets_entry_id'), 'entry_sets', ['entry_id'], unique=False)
    op.create_index(op.f('ix_entry_sets_id'), 'entry_sets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entry_sets_id'), table_name='entry_sets')
    op.drop_index(op.f('ix_entry_sets_entry_id'), table_name='entry_sets')
    op.drop_table('entry_sets')
    op.drop_index(op.f('ix_round_entries_round_id'), table_name='round_entries')
    op.drop_index(op.f('ix_round_entries_pattern_id'), table_name='round_entries')
    op.drop_index(op.f('ix_round_entries_id'), table_name='round_entries')
    op.drop_index(op.f('ix_round_entries_exercise_id'), table_name='round_entries')
    op.drop_table('round_entries')
    op.drop_index(op.f('ix_superset_rounds_session_id'), table_name='superset_rounds')
    op.drop_index(op.f('ix_superset_rounds_id'), table_name='superset_rounds')
    op.drop_table('superset_rounds')
    op.drop_index(op.f('ix_training_sessions_user_id'), table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_id'), table_name='training_sessions')
    op.drop_table('training_sessions')
    # ### end Alembic commands ###
