"""add_primary_muscle_group_id_to_routine_slots

Revision ID: 93a81aa99814
Revises: a1ceab703b44
Create Date: 2026-01-28 21:57:53.247124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93a81aa99814'
down_revision = 'a1ceab703b44'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routine_slots', sa.Column('primary_muscle_group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'routine_slots', 'muscle_groups', ['primary_muscle_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'routine_slots', type_='foreignkey')
    op.drop_column('routine_slots', 'primary_muscle_group_id')
    # ### end Alembic commands ###
