"""add_rpe_to_workout_sets

Revision ID: 98ca78ffdf3e
Revises: 1e78fc4b5fa4
Create Date: 2026-01-11 22:36:47.072491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98ca78ffdf3e'
down_revision = '1e78fc4b5fa4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_sets', sa.Column('rpe', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_sets', 'rpe')
    # ### end Alembic commands ###
