"""add exercise_pattern_map

Revision ID: a3bb66cde5d6
Revises: 51a278328365
Create Date: 2026-08-01 16:41:59.841291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3bb66cde5d6'
down_revision = '51a278328365'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_pattern_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('pattern_id', sa.Integer(), nullable=False),
    sa.Column('is_override', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['pattern_id'], ['movement_patterns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_pattern_map_exercise_id'), 'exercise_pattern_map', ['exercise_id'], unique=True)
    op.create_index(op.f('ix_exercise_pattern_map_id'), 'exercise_pattern_map', ['id'], unique=False)
    op.create_index(op.f('ix_exercise_pattern_map_pattern_id'), 'exercise_pattern_map', ['pattern_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercise_pattern_map_pattern_id'), table_name='exercise_pattern_map')
    op.drop_index(op.f('ix_exercise_pattern_map_id'), table_name='exercise_pattern_map')
    op.drop_index(op.f('ix_exercise_pattern_map_exercise_id'), table_name='exercise_pattern_map')
    op.drop_table('exercise_pattern_map')
    # ### end Alembic commands ###
