"""add slot_templates table

Revision ID: a72f10231719
Revises: 5084736020fd
Create Date: 2026-01-04 14:52:46.105229

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a72f10231719'
down_revision = '5084736020fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slot_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slot_type', sa.Enum('standard', 'warmup', 'finisher', 'active_recovery', 'wildcard', name='slottype'), nullable=False),
    sa.Column('muscle_group_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=True),
    sa.Column('default_exercise_id', sa.Integer(), nullable=True),
    sa.Column('target_sets', sa.Integer(), nullable=True),
    sa.Column('target_reps_min', sa.Integer(), nullable=True),
    sa.Column('target_reps_max', sa.Integer(), nullable=True),
    sa.Column('target_weight', sa.Float(), nullable=True),
    sa.Column('target_rest_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['default_exercise_id'], ['exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slot_templates_id'), 'slot_templates', ['id'], unique=False)
    op.create_index(op.f('ix_slot_templates_name'), 'slot_templates', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slot_templates_name'), table_name='slot_templates')
    op.drop_index(op.f('ix_slot_templates_id'), table_name='slot_templates')
    op.drop_table('slot_templates')
    # ### end Alembic commands ###
