"""add weekly_volume table

Revision ID: a8639382ac85
Revises: d25a1cdb916b
Create Date: 2026-01-04 15:05:38.720592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8639382ac85'
down_revision = 'd25a1cdb916b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_volume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('muscle_group_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('total_sets', sa.Integer(), nullable=False),
    sa.Column('total_reps', sa.Integer(), nullable=False),
    sa.Column('total_volume', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['muscle_group_id'], ['muscle_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('muscle_group_id', 'week_start', name='uq_weekly_volume_muscle_group_week')
    )
    op.create_index(op.f('ix_weekly_volume_id'), 'weekly_volume', ['id'], unique=False)
    op.create_index(op.f('ix_weekly_volume_muscle_group_id'), 'weekly_volume', ['muscle_group_id'], unique=False)
    op.create_index(op.f('ix_weekly_volume_week_start'), 'weekly_volume', ['week_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_volume_week_start'), table_name='weekly_volume')
    op.drop_index(op.f('ix_weekly_volume_muscle_group_id'), table_name='weekly_volume')
    op.drop_index(op.f('ix_weekly_volume_id'), table_name='weekly_volume')
    op.drop_table('weekly_volume')
    # ### end Alembic commands ###
