"""add personal_records table

Revision ID: d25a1cdb916b
Revises: 5077e7889e05
Create Date: 2026-01-04 15:03:17.444010

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd25a1cdb916b'
down_revision = '5077e7889e05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.Enum('weight', 'reps', 'volume', 'time', name='recordtype'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workout_session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['workout_session_id'], ['workout_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_records_achieved_at'), 'personal_records', ['achieved_at'], unique=False)
    op.create_index(op.f('ix_personal_records_exercise_id'), 'personal_records', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_personal_records_id'), 'personal_records', ['id'], unique=False)
    op.create_index(op.f('ix_personal_records_record_type'), 'personal_records', ['record_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_personal_records_record_type'), table_name='personal_records')
    op.drop_index(op.f('ix_personal_records_id'), table_name='personal_records')
    op.drop_index(op.f('ix_personal_records_exercise_id'), table_name='personal_records')
    op.drop_index(op.f('ix_personal_records_achieved_at'), table_name='personal_records')
    op.drop_table('personal_records')
    # ### end Alembic commands ###
