"""add users table and update foreign keys

Revision ID: e5b14fa30dfc
Revises: 4eedf400be74
Create Date: 2026-01-06 20:07:52.801866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5b14fa30dfc'
down_revision = '4eedf400be74'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('preferred_units', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_device_id'), 'users', ['device_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    
    # Add columns as nullable first, then populate with default user, then make non-nullable
    # Create a default user for any existing data
    connection = op.get_bind()
    result = connection.execute(sa.text("SELECT COUNT(*) FROM equipment_profiles"))
    has_existing_data = result.scalar() > 0
    
    default_user_id = None
    if has_existing_data:
        # Create a default user for existing data
        connection.execute(sa.text(
            "INSERT INTO users (device_id, display_name, preferred_units, is_active) "
            "VALUES ('migration-default-user', 'Migration User', 'lbs', true) RETURNING id"
        ))
        default_user_id = connection.execute(sa.text("SELECT id FROM users WHERE device_id = 'migration-default-user'")).scalar()
    
    # Add columns as nullable first
    op.add_column('equipment_profiles', sa.Column('user_id', sa.Integer(), nullable=True))
    if default_user_id:
        connection.execute(sa.text(f"UPDATE equipment_profiles SET user_id = {default_user_id} WHERE user_id IS NULL"))
    op.alter_column('equipment_profiles', 'user_id', nullable=False)
    op.create_index(op.f('ix_equipment_profiles_user_id'), 'equipment_profiles', ['user_id'], unique=False)
    op.create_foreign_key(None, 'equipment_profiles', 'users', ['user_id'], ['id'])
    
    op.add_column('personal_records', sa.Column('user_id', sa.Integer(), nullable=True))
    if default_user_id:
        connection.execute(sa.text(f"UPDATE personal_records SET user_id = {default_user_id} WHERE user_id IS NULL"))
    op.alter_column('personal_records', 'user_id', nullable=False)
    op.create_index(op.f('ix_personal_records_user_id'), 'personal_records', ['user_id'], unique=False)
    op.create_foreign_key(None, 'personal_records', 'users', ['user_id'], ['id'])
    
    op.add_column('routine_templates', sa.Column('user_id', sa.Integer(), nullable=True))
    if default_user_id:
        connection.execute(sa.text(f"UPDATE routine_templates SET user_id = {default_user_id} WHERE user_id IS NULL"))
    op.alter_column('routine_templates', 'user_id', nullable=False)
    op.create_index(op.f('ix_routine_templates_user_id'), 'routine_templates', ['user_id'], unique=False)
    op.create_foreign_key(None, 'routine_templates', 'users', ['user_id'], ['id'])
    
    op.add_column('weekly_volume', sa.Column('user_id', sa.Integer(), nullable=True))
    if default_user_id:
        connection.execute(sa.text(f"UPDATE weekly_volume SET user_id = {default_user_id} WHERE user_id IS NULL"))
    op.alter_column('weekly_volume', 'user_id', nullable=False)
    op.drop_constraint(op.f('uq_weekly_volume_muscle_group_week'), 'weekly_volume', type_='unique')
    op.create_index(op.f('ix_weekly_volume_user_id'), 'weekly_volume', ['user_id'], unique=False)
    op.create_unique_constraint('uq_weekly_volume_muscle_group_week_user', 'weekly_volume', ['muscle_group_id', 'week_start', 'user_id'])
    op.create_foreign_key(None, 'weekly_volume', 'users', ['user_id'], ['id'])
    
    op.add_column('workout_sessions', sa.Column('user_id', sa.Integer(), nullable=True))
    if default_user_id:
        connection.execute(sa.text(f"UPDATE workout_sessions SET user_id = {default_user_id} WHERE user_id IS NULL"))
    op.alter_column('workout_sessions', 'user_id', nullable=False)
    op.create_index(op.f('ix_workout_sessions_user_id'), 'workout_sessions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'workout_sessions', 'users', ['user_id'], ['id'])
    
    # Update user_injuries: change nullable=True to nullable=False and add foreign key
    if default_user_id:
        connection.execute(sa.text(f"UPDATE user_injuries SET user_id = {default_user_id} WHERE user_id IS NULL"))
    op.alter_column('user_injuries', 'user_id',
                    existing_type=sa.Integer(),
                    nullable=False)
    op.create_index(op.f('ix_user_injuries_user_id'), 'user_injuries', ['user_id'], unique=False)
    op.create_foreign_key(None, 'user_injuries', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_injuries', type_='foreignkey')
    op.drop_index(op.f('ix_user_injuries_user_id'), table_name='user_injuries')
    op.alter_column('user_injuries', 'user_id',
                    existing_type=sa.Integer(),
                    nullable=True)
    op.drop_constraint(None, 'workout_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_workout_sessions_user_id'), table_name='workout_sessions')
    op.drop_column('workout_sessions', 'user_id')
    op.drop_constraint(None, 'weekly_volume', type_='foreignkey')
    op.drop_constraint('uq_weekly_volume_muscle_group_week_user', 'weekly_volume', type_='unique')
    op.drop_index(op.f('ix_weekly_volume_user_id'), table_name='weekly_volume')
    op.create_unique_constraint(op.f('uq_weekly_volume_muscle_group_week'), 'weekly_volume', ['muscle_group_id', 'week_start'], postgresql_nulls_not_distinct=False)
    op.drop_column('weekly_volume', 'user_id')
    op.drop_constraint(None, 'routine_templates', type_='foreignkey')
    op.drop_index(op.f('ix_routine_templates_user_id'), table_name='routine_templates')
    op.drop_column('routine_templates', 'user_id')
    op.drop_constraint(None, 'personal_records', type_='foreignkey')
    op.drop_index(op.f('ix_personal_records_user_id'), table_name='personal_records')
    op.drop_column('personal_records', 'user_id')
    op.drop_constraint(None, 'equipment_profiles', type_='foreignkey')
    op.drop_index(op.f('ix_equipment_profiles_user_id'), table_name='equipment_profiles')
    op.drop_column('equipment_profiles', 'user_id')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_device_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
