/**
 * Create Variant Dialog Component
 * Dialog for creating exercise variants for context-aware history tracking
 */
import { useState } from 'react'
import { exerciseApi, Exercise } from '../services/exercises'

interface CreateVariantDialogProps {
  exercise: Exercise
  workoutStyle?: string | null
  onClose: () => void
  onCreated: () => void
}

const VARIANT_TYPES = ['HIIT', 'Strength', 'Volume', 'Endurance', 'Custom']

export default function CreateVariantDialog({
  exercise,
  workoutStyle,
  onClose,
  onCreated
}: CreateVariantDialogProps) {
  const [variantType, setVariantType] = useState<string>(() => {
    // Auto-select based on workout style
    if (workoutStyle === 'HIIT') return 'HIIT'
    if (workoutStyle === 'strength' || workoutStyle === '5x5') return 'Strength'
    if (workoutStyle === 'volume') return 'Volume'
    return 'Custom'
  })
  const [variantName, setVariantName] = useState('')
  const [defaultSets, setDefaultSets] = useState<number | ''>('')
  const [defaultReps, setDefaultReps] = useState<number | ''>('')
  const [defaultWeight, setDefaultWeight] = useState<number | ''>('')
  const [defaultTimeSeconds, setDefaultTimeSeconds] = useState<number | ''>('')
  const [defaultRestSeconds, setDefaultRestSeconds] = useState<number | ''>('')
  const [creating, setCreating] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const handleCreate = async () => {
    if (!variantType) {
      setError('Please select a variant type')
      return
    }

    setCreating(true)
    setError(null)

    try {
      await exerciseApi.duplicate(exercise.id, {
        name: variantName || undefined, // If empty, will auto-generate
        variant_type: variantType,
        default_sets: defaultSets ? Number(defaultSets) : undefined,
        default_reps: defaultReps ? Number(defaultReps) : undefined,
        default_weight: defaultWeight ? Number(defaultWeight) : undefined,
        default_time_seconds: defaultTimeSeconds ? Number(defaultTimeSeconds) : undefined,
        default_rest_seconds: defaultRestSeconds ? Number(defaultRestSeconds) : undefined,
      })
      onCreated()
    } catch (err: any) {
      setError(err?.response?.data?.detail || err?.message || 'Failed to create variant')
    } finally {
      setCreating(false)
    }
  }

  const autoGeneratedName = variantName || `${exercise.name} (${variantType})`

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
      <div className="bg-white rounded-lg shadow-xl p-6 max-w-md w-full mx-4 max-h-[90vh] overflow-y-auto">
        <h3 className="text-lg font-semibold mb-4">Create Exercise Variant</h3>
        <p className="text-sm text-gray-600 mb-4">
          Create a variant of "{exercise.name}" for context-aware history tracking. 
          Each variant maintains its own performance history.
        </p>

        {error && (
          <div className="mb-4 p-3 bg-red-100 text-red-700 rounded text-sm">
            {error}
          </div>
        )}

        <div className="space-y-4">
          {/* Variant Type */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Variant Type <span className="text-red-500">*</span>
            </label>
            <select
              value={variantType}
              onChange={(e) => setVariantType(e.target.value)}
              className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
            >
              {VARIANT_TYPES.map(type => (
                <option key={type} value={type}>{type}</option>
              ))}
            </select>
          </div>

          {/* Variant Name */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Variant Name (Optional)
            </label>
            <input
              type="text"
              value={variantName}
              onChange={(e) => setVariantName(e.target.value)}
              placeholder={autoGeneratedName}
              className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
            />
            <p className="text-xs text-gray-500 mt-1">
              If not provided, will be: {autoGeneratedName}
            </p>
          </div>

          {/* Default Parameters */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Default Parameters (Optional)
            </label>
            <p className="text-xs text-gray-500 mb-3">
              Set default parameters for this variant. These will be suggested during workouts.
            </p>
            <div className="grid grid-cols-2 gap-3">
              <div>
                <label className="block text-xs text-gray-600 mb-1">Sets</label>
                <input
                  type="number"
                  value={defaultSets}
                  onChange={(e) => setDefaultSets(e.target.value ? Number(e.target.value) : '')}
                  placeholder="e.g., 3"
                  className="w-full px-2 py-1.5 text-sm border border-gray-300 rounded focus:outline-none focus:ring-1 focus:ring-blue-500"
                />
              </div>
              <div>
                <label className="block text-xs text-gray-600 mb-1">Reps</label>
                <input
                  type="number"
                  value={defaultReps}
                  onChange={(e) => setDefaultReps(e.target.value ? Number(e.target.value) : '')}
                  placeholder="e.g., 12"
                  className="w-full px-2 py-1.5 text-sm border border-gray-300 rounded focus:outline-none focus:ring-1 focus:ring-blue-500"
                />
              </div>
              <div>
                <label className="block text-xs text-gray-600 mb-1">Weight (lbs)</label>
                <input
                  type="number"
                  step="0.5"
                  value={defaultWeight}
                  onChange={(e) => setDefaultWeight(e.target.value ? Number(e.target.value) : '')}
                  placeholder="e.g., 25"
                  className="w-full px-2 py-1.5 text-sm border border-gray-300 rounded focus:outline-none focus:ring-1 focus:ring-blue-500"
                />
              </div>
              <div>
                <label className="block text-xs text-gray-600 mb-1">Time (seconds)</label>
                <input
                  type="number"
                  value={defaultTimeSeconds}
                  onChange={(e) => setDefaultTimeSeconds(e.target.value ? Number(e.target.value) : '')}
                  placeholder="e.g., 30"
                  className="w-full px-2 py-1.5 text-sm border border-gray-300 rounded focus:outline-none focus:ring-1 focus:ring-blue-500"
                />
              </div>
              <div className="col-span-2">
                <label className="block text-xs text-gray-600 mb-1">Rest (seconds)</label>
                <input
                  type="number"
                  value={defaultRestSeconds}
                  onChange={(e) => setDefaultRestSeconds(e.target.value ? Number(e.target.value) : '')}
                  placeholder="e.g., 60"
                  className="w-full px-2 py-1.5 text-sm border border-gray-300 rounded focus:outline-none focus:ring-1 focus:ring-blue-500"
                />
              </div>
            </div>
          </div>
        </div>

        {/* Actions */}
        <div className="mt-6 flex justify-end gap-3">
          <button
            onClick={onClose}
            disabled={creating}
            className="px-4 py-2 text-sm border border-gray-300 rounded hover:bg-gray-50 disabled:opacity-50"
          >
            Cancel
          </button>
          <button
            onClick={handleCreate}
            disabled={creating || !variantType}
            className="px-4 py-2 text-sm bg-blue-600 text-white rounded hover:bg-blue-700 disabled:opacity-50"
          >
            {creating ? 'Creating...' : 'Create Variant'}
          </button>
        </div>
      </div>
    </div>
  )
}
